version: '3'
services:
  web:
    build: .
    container_name: convertz-local
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      SECURITY: disabled
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
    restart: unless-stopped