services:
  convertz-local:
    build: .
    container_name: convertz-local
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      SECURITY: disabled
      API_KEY: none
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
    restart: unless-stopped
