services:
  convertz:
    image: ghcr.io/arthur2500/convertz:latest
    container_name: convertz
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      SECURITY: enabled
      API_KEY: none
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
    restart: unless-stopped
